/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "pro-my-ui",
  "description": "网站描述",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {
        "home": false,
        "actionText": "开始使用",
        "actionLink": "/pages/test/",
        "features": [
          {
            "title": "heaven-UI",
            "details": "一套基于 Vue.js 的高质量UI 组件库"
          }
        ],
        "footer": "MIT Licensed | COPYRIGHT ©"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1ac5d586",
      "path": "/"
    },
    {
      "title": "安装",
      "frontmatter": {
        "title": "安装"
      },
      "regularPath": "/component/installation/installation.html",
      "relativePath": "component/installation/installation.md",
      "key": "v-52daa784",
      "path": "/component/installation/installation.html",
      "headers": [
        {
          "level": 2,
          "title": "NPM安装",
          "slug": "npm安装"
        }
      ]
    },
    {
      "title": "快速上手",
      "frontmatter": {
        "title": "快速上手"
      },
      "regularPath": "/component/quickstart/quickstart.html",
      "relativePath": "component/quickstart/quickstart.md",
      "key": "v-1c28f104",
      "path": "/component/quickstart/quickstart.html",
      "headers": [
        {
          "level": 2,
          "title": "引入pro-my-ui",
          "slug": "引入pro-my-ui"
        }
      ]
    },
    {
      "title": "MyTable表格",
      "frontmatter": {
        "title": "MyTable表格"
      },
      "regularPath": "/component/test/test.html",
      "relativePath": "component/test/test.md",
      "key": "v-1af3893e",
      "path": "/component/test/test.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        }
      ]
    },
    {
      "title": "MyTable表格",
      "frontmatter": {
        "title": "MyTable表格"
      },
      "regularPath": "/component/table/table.html",
      "relativePath": "component/table/table.md",
      "key": "v-d4201978",
      "path": "/component/table/table.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [],
    "sidebar": [
      {
        "title": "开发指南",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/component/installation/installation.md",
          "/component/quickstart/quickstart.md"
        ]
      },
      {
        "title": "组件",
        "collapsable": false,
        "sidebarDepth": 0,
        "children": [
          "/component/table/table.md"
        ]
      }
    ]
  }
}