/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "pro-my-ui",
  "description": "网站描述",
  "base": "/pro-my-ui/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/pro-my-ui/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "快速上手",
      "frontmatter": {
        "title": "快速上手"
      },
      "regularPath": "/component/quickstart/quickstart.html",
      "relativePath": "component/quickstart/quickstart.md",
      "key": "v-1c28f104",
      "path": "/component/quickstart/quickstart.html",
      "headers": [
        {
          "level": 2,
          "title": "引入pro-my-ui",
          "slug": "引入pro-my-ui"
        }
      ]
    },
    {
      "frontmatter": {
        "home": false,
        "actionText": "开始使用",
        "actionLink": "/pages/test/",
        "features": [
          {
            "title": "heaven-UI",
            "details": "一套基于 Vue.js 的高质量UI 组件库"
          }
        ],
        "footer": "MIT Licensed | COPYRIGHT ©"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1ac5d586",
      "path": "/"
    },
    {
      "title": "安装",
      "frontmatter": {
        "title": "安装"
      },
      "regularPath": "/component/installation/installation.html",
      "relativePath": "component/installation/installation.md",
      "key": "v-52daa784",
      "path": "/component/installation/installation.html",
      "headers": [
        {
          "level": 2,
          "title": "NPM安装",
          "slug": "npm安装"
        }
      ]
    },
    {
      "title": "MyTable表格",
      "frontmatter": {
        "title": "MyTable表格"
      },
      "regularPath": "/component/table/table.html",
      "relativePath": "component/table/table.md",
      "key": "v-d4201978",
      "path": "/component/table/table.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        },
        {
          "level": 3,
          "title": "MyTable（属性）",
          "slug": "mytable-属性"
        },
        {
          "level": 3,
          "title": "Column 配置",
          "slug": "column-配置"
        },
        {
          "level": 3,
          "title": "搜索项 配置（SearchProps）",
          "slug": "搜索项-配置-searchprops"
        },
        {
          "level": 3,
          "title": "MyTable 方法",
          "slug": "mytable-方法"
        },
        {
          "level": 3,
          "title": "MyTable 插槽",
          "slug": "mytable-插槽"
        }
      ]
    },
    {
      "title": "MyForm表单",
      "frontmatter": {
        "title": "MyForm表单"
      },
      "regularPath": "/component/form/form.html",
      "relativePath": "component/form/form.md",
      "key": "v-4b5fb13e",
      "path": "/component/form/form.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        },
        {
          "level": 3,
          "title": "MyForm(属性)",
          "slug": "myform-属性"
        },
        {
          "level": 3,
          "title": "setFormConfig(表单配置)",
          "slug": "setformconfig-表单配置"
        },
        {
          "level": 3,
          "title": "formList(表单列表结构)",
          "slug": "formlist-表单列表结构"
        },
        {
          "level": 3,
          "title": "formBtn(表单列表结构)",
          "slug": "formbtn-表单列表结构"
        },
        {
          "level": 3,
          "title": "MyForm 方法",
          "slug": "myform-方法"
        },
        {
          "level": 3,
          "title": "MyForm(插槽)",
          "slug": "myform-插槽"
        }
      ]
    },
    {
      "title": "MyTable表格",
      "frontmatter": {
        "title": "MyTable表格"
      },
      "regularPath": "/component/test/test.html",
      "relativePath": "component/test/test.md",
      "key": "v-1af3893e",
      "path": "/component/test/test.html",
      "headers": [
        {
          "level": 2,
          "title": "基本用法",
          "slug": "基本用法"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "GitHub",
        "link": "https://github.com/lifechang/pro-my-ui"
      }
    ],
    "sidebar": [
      {
        "title": "开发指南",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/component/installation/installation.md",
          "/component/quickstart/quickstart.md"
        ]
      },
      {
        "title": "组件",
        "collapsable": false,
        "sidebarDepth": 0,
        "children": [
          "/component/table/table.md",
          "/component/form/form.md"
        ]
      }
    ]
  }
}